#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker007"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4dbadbfe9db149538de9dcb1f3af54cc" }
]

[assets]
directory = "./public"
